# How to build Logic Gate Neural Network

## And Gate

In [1]:
import numpy as np 

def sigmoid(x):
    return 1.0/(1+ np.exp(-x))

class AND:
    def __init__(self, x):
        self.input      = x
        self.weights    = np.array([-30, 20, 20])      
        
    def feedforward(self):
        self.output = sigmoid(np.dot(self.input, self.weights))
        
        
X = np.array([[1,0,0],
              [1,0,1],
              [1,1,0],
              [1,1,1]])
nn = AND(X)
nn.feedforward()
Y = nn.output
print(Y.round(3))

[0. 0. 0. 1.]


## Or Gate

In [2]:
import numpy as np 

def sigmoid(x):
    return 1.0/(1+ np.exp(-x))

class OR:
    def __init__(self, x):
        self.input      = x
        self.weights    = np.array([-10, 20, 20])      
        
    def feedforward(self):
        self.output = sigmoid(np.dot(self.input, self.weights))
        
        
X = np.array([[1,0,0],
              [1,0,1],
              [1,1,0],
              [1,1,1]])
nn = OR(X)
nn.feedforward()
Y = nn.output
print(Y.round(3))

[0. 1. 1. 1.]


## NAND Gate

In [3]:
import numpy as np 

def sigmoid(x):
    return 1.0/(1+ np.exp(-x))

class NAND:
    def __init__(self, x):
        self.input      = x
        self.weights    = np.array([30, -20, -20])      
        
    def feedforward(self):
        self.output = sigmoid(np.dot(self.input, self.weights))
        
        
X = np.array([[1,0,0],
              [1,0,1],
              [1,1,0],
              [1,1,1]])
nn = NAND(X)
nn.feedforward()
Y = nn.output
print(Y.round(3))

[1. 1. 1. 0.]


## NOR Gate

In [4]:
import numpy as np 

def sigmoid(x):
    return 1.0/(1+ np.exp(-x))

class NOR:
    def __init__(self, x):
        self.input      = x
        self.weights    = np.array([10, -20, -20])      
        
    def feedforward(self):
        self.output = sigmoid(np.dot(self.input, self.weights))
        
        
X = np.array([[1,0,0],
              [1,0,1],
              [1,1,0],
              [1,1,1]])
nn = NOR(X)
nn.feedforward()
Y = nn.output
print(Y.round(3))

[1. 0. 0. 0.]


## XOR Gate

In [5]:
import numpy as np 

def sigmoid(x):
    return 1.0/(1+ np.exp(-x))

class XOR:
    def __init__(self, x):
        self.input      = x
        weights_NOR     = np.array([10, -20, -20]) 
        weights_AND     = np.array([-30, 20, 20])    
        self.weights1   = np.array([weights_NOR, weights_AND]).T
        self.weights2   = weights_NOR
        
    def feedforward(self):
        self.layer1 = sigmoid(np.dot(self.input, self.weights1))
        bias = np.ones(len(self.layer1))
        self.layer1 = np.insert(self.layer1,0,values = bias, axis =1)
        self.output = sigmoid(np.dot(self.layer1, self.weights2))
        
        
X = np.array([[1,0,0],
              [1,0,1],
              [1,1,0],
              [1,1,1]])
nn = XOR(X)
nn.feedforward()
Y = nn.output
print(Y.round(3))

[0. 1. 1. 0.]
